image: hipay/gitlab-ci-base:jessie

variables:
  PROJECT_NAME_TEST_1:  ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}_1

.clean_docker_compose: &clean_docker_compose
  after_script:
    - /tools/clean-job.sh $PROJECT_NAME_TEST_1 docker-compose.test.yml mirakl ${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}

stages:
 - build-test
 - test
 - clean-stack
 - analysis
 - build
 - deploy
 - sync

build-test:
  stage: build-test
  script:
    - docker-compose -f docker-compose.test.yml build
  allow_failure: false
  tags:
    - pi-commerce-no-overlay

test:
  stage: test
  tags:
    - pi-commerce-no-overlay
  before_script:
    - npm install yamljs
    - chmod -R 766 ./bin/config
    - chmod u+x bin/docker/gitlab/substitute.sh
    - ./bin/docker/gitlab/substitute.sh ./bin/docker/conf/test/hipay.env.dist
    - docker-compose -p $PROJECT_NAME_TEST_1 -f docker-compose.test.yml stop
    - docker-compose -p $PROJECT_NAME_TEST_1 -f docker-compose.test.yml rm -fv
    - docker-compose -p $PROJECT_NAME_TEST_1 -f docker-compose.test.yml up -d
    - sleep 450
    - docker-compose -p $PROJECT_NAME_TEST_1 -f docker-compose.test.yml logs
  script:
    - curl --retry 10 --retry-delay 5 -v ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_web/web/index.php
    - docker cp ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_web:/var/www/html/vendor ./
    - sh bin/tests/import_test_data.sh $PROJECT_NAME_TEST_1
    - sh bin/tests/casper_run_circle.sh http://${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}-web/web/index.php
  allow_failure: false
  artifacts:
      paths:
      - bin/tests/errors
      when: always
  <<: *clean_docker_compose

clean-stack-test:
  stage: clean-stack
  script:
    - echo "Clean remaining containers, network and images"
  <<: *clean_docker_compose
  tags:
    - pi-commerce-no-overlay
  when: always


sonarqube:
  stage: analysis
  tags:
    - pi-commerce-no-overlay
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.17.0.1:19000
    SONAR_ANALYSIS_MODE: preview
    SONAR_TOKEN: $SONAR_LOGIN
  script:
  - /usr/bin/sonar-scanner-run.sh -X

sonarqube-reports:
  stage: analysis
  tags:
    - pi-commerce-no-overlay
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://172.17.0.1:19000
    SONAR_ANALYSIS_MODE: "publish"
    SONAR_TOKEN: $SONAR_LOGIN
  script:
  - unset CI_BUILD_REF && /usr/bin/sonar-scanner-run.sh


build:
  stage: build
  before_script:
    - /tools/docker-rmi.sh ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  script:
    - docker-compose -f docker-compose.acceptance.yml build
    - docker-compose -f docker-compose.acceptance.yml push
  after_script:
    - docker rmi ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
  tags:
    - pi-commerce-no-overlay

deploy2acceptance:
  stage: deploy
  tags:
    - pi-commerce-no-overlay
  script:
    - chmod u+x bin/docker/gitlab/substitute.sh
    - ./bin/docker/gitlab/substitute.sh ./bin/docker/conf/acceptance/hipay.env.dist
    - echo "Deploy from registry"
      # Substitute env variables which dont exists on the distant machine
    - /tools/substitute-env-var.sh docker-compose.acceptance.yml
      # Change path for relative path to environment files
    - sed -i -e "s|bin/docker/conf/acceptance/hipay.env.dist|hipay.env.dist|g" docker-compose.acceptance.yml
      # Push file on distant machine and launch deploy
    - bash /tools/deployToDockerMachine.sh -e ./bin/docker/conf/acceptance/hipay.env.dist -s docker-compose.acceptance.yml -n $DOCKER_STACK-$DOCKER_SERVICE-$CI_COMMIT_REF_SLUG
  allow_failure: false

sync:
  stage: sync
  tags:
    - pi-commerce-no-overlay
  script:
  - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-wallet-cashout-mirakl-integration.git
  - cd hipay-wallet-cashout-mirakl-integration.git
  - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-wallet-cashout-mirakl-integration.git
  allow_failure: true
