image: $REGISTRY_CI/gitlab-ci-base:buster

stages:
 - build-test
 - test

services:
 - name: $CI_REGISTRY/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
   alias: mirakl
 - name: mysql:5.7
   alias: database

build-test:
  stage: build-test
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
  script:
    - /kaniko/executor
      --cache=true
      --context "dir://${CI_PROJECT_DIR}"
      --dockerfile "./bin/docker/images/mirakl/Dockerfile"
      --destination "$CI_REGISTRY/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}"
  allow_failure: false
  tags:
    - small

test:
  stage: test
  tags:
    - small
  variables:
    MIRAKL_CONNECTOR_ACCOUNT_OPERATOR_EMAIL: $MIRAKL_CONNECTOR_ACCOUNT_OPERATOR_EMAIL
    MIRAKL_CONNECTOR_ACCOUNT_OPERATOR_HIPAY_ID: $MIRAKL_CONNECTOR_ACCOUNT_OPERATOR_HIPAY_ID
    MIRAKL_CONNECTOR_ACCOUNT_TECHNICAL_EMAIL: $MIRAKL_CONNECTOR_ACCOUNT_TECHNICAL_EMAIL
    MIRAKL_CONNECTOR_ACCOUNT_TECHNICAL_HIPAY_ID: $MIRAKL_CONNECTOR_ACCOUNT_TECHNICAL_HIPAY_ID
    MIRAKL_CONNECTOR_HIPAY_BASE_SOAP_URL: $MIRAKL_CONNECTOR_HIPAY_BASE_SOAP_URL
    MIRAKL_CONNECTOR_HIPAY_ENTITY: $MIRAKL_CONNECTOR_HIPAY_ENTITY
    MIRAKL_CONNECTOR_HIPAY_MERCHANT_GROUP_ID: $MIRAKL_CONNECTOR_HIPAY_MERCHANT_GROUP_ID
    MIRAKL_CONNECTOR_HIPAY_WS_LOGIN: $MIRAKL_CONNECTOR_HIPAY_WS_LOGIN
    MIRAKL_CONNECTOR_HIPAY_WS_PASSWORD: $MIRAKL_CONNECTOR_HIPAY_WS_PASSWORD
    MIRAKL_CONNECTOR_MIRAKL_BASE_URL: $MIRAKL_CONNECTOR_MIRAKL_BASE_URL
    MIRAKL_CONNECTOR_MIRAKL_FRONT_KEY: $MIRAKL_CONNECTOR_MIRAKL_FRONT_KEY
    MIRAKL_CONNECTOR_MIRAKL_OPERATOR_KEY: $MIRAKL_CONNECTOR_MIRAKL_OPERATOR_KEY
    MIRAKL_CONNECTOR_MIRAKL_SHOP_KEY: $MIRAKL_CONNECTOR_MIRAKL_SHOP_KEY
    MIRAKL_CONNECTOR_HIPAY_BASE_REST_URL: $MIRAKL_CONNECTOR_HIPAY_BASE_REST_URL
    GITHUB_TOKEN: $GITHUB_TOKEN
    MIRAKL_CONNECTOR_MIRAKL_DB_HOST: database
    ENV: test
  script:
    - curl --retry 10 --retry-delay 5 -v http://mirakl/web/index.php
    - sh bin/tests/casper_run_circle.sh http:\/\/mirakl/web/index.php
  allow_failure: false
  artifacts:
      paths:
      - bin/tests/errors
      when: always
