web:
  container_name: sdf
  ports:
    - "8099:80"
  env_file:
    - ./docker/conf/production/hipay.env.dist
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
db:
  container_name: ss
  ports:
    - "3309:3306"
smtp:
  container_name: bbb
  ports:
    - "1099:1080"
