web:
  container_name: {CONTAINER_NAME_WEB}
  ports:
    - "{PORT_WEB}:80"
  env_file:
    - ./docker/conf/production/hipay.env.dist
db:
  image: mysql
  container_name: {CONTAINER_NAME_MYSQL}
  ports:
    - "{PORT_MYSQL}:3306"
smtp:
  container_name: {CONTAINER_NAME_SMTP}
  ports:
    - "{PORT_SMTP}:1080"
