web:
  container_name: {CONTAINER_NAME_WEB}
  ports:
    - "{PORT_WEB}:80"
  env_file:
    - ./docker/conf/production/hipay.env.dist
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
db:
  container_name: {CONTAINER_NAME_MYSQL}
  ports:
    - "{PORT_MYSQL}:3306"
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
smtp:
  container_name: {CONTAINER_NAME_SMTP}
  ports:
    - "{PORT_SMTP}:1080"
  labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
