web:
  container_name: hipay-mirakl-running
  env_file:
    - ./docker/conf/stage/hipay.env.dist
  ports:
    - "8080:80"
  volumes:
    - ./config:/var/www/html/config
    - ./vendor:/var/www/html/vendor
db:
  image: mysql
  container_name: hipay-mirakl-db-running
  ports:
    - "2563:3306"
smtp:
  container_name: hipay-mirakl-smtp-running
  ports:
    - "1089:1080"
