web:
  container_name: qdqsd
  ports:
    - "8096:80"
  env_file:
    - ./docker/conf/production/hipay.env.dist
db:
  image: mysql
  container_name: qsd
  ports:
    - "3366:3306"
smtp:
  container_name: qd
  ports:
    - "1093:1080"
