version: "3.3"

networks:
  traefik_traefik:
    external: true
  mirakl:
    internal: true
  outside-pi-overlay:
    external: true

services:
  web:
    restart: on-failure:5
    build:
     context: .
     dockerfile: ./bin/docker/images/mirakl/Dockerfile
    image: ${REGISTRY_URL}/${DOCKER_STACK}-${DOCKER_SERVICE}_web:${CI_COMMIT_REF_SLUG}
    env_file:
      - ./bin/docker/conf/acceptance/hipay.env.dist
    networks:
      - traefik_traefik
      - mirakl
      - outside-pi-overlay

    labels:
      - "com.hipay.ir.publish=1"
      - "com.hipay.ir.name=web"
      - "com.hipay.ir.branch=${CI_COMMIT_REF_SLUG}"
      - "com.hipay.ir.gitlab.feature.link=${CI_PROJECT_URL}/tree/${CI_COMMIT_REF_NAME}"
      - "com.hipay.ir.gitlab.org=pi-ecommerce"
      - "com.hipay.ir.gitlab.project=hipay-wallet-cashout-mirakl-integration"
      - "com.hipay.ir.admin.url=${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com"
    deploy:
      labels:
        - "traefik.frontend.rule=Host:${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}.hipay-pos-platform.com"
        - "traefik.port=80"
        - "traefik.docker.network=traefik_traefik"
  database:
    restart: on-failure:5
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app
    networks:
      mirakl:
        aliases:
          - ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}-database
#  smtp:
#    restart: on-failure:5
#    image: schickling/mailcatcher
#    networks:
#      traefik_traefik:
#      mirakl:
#        aliases:
#          - ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}-smtp
#    deploy:
#      labels:
#        - "traefik.frontend.rule=Host:${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-smtp.hipay-pos-platform.com"
#        - "traefik.port=1080"
#        - "traefik.docker.network=traefik_traefik"
