parameters:
   
    # In dev, all emails are catched and not really sent
    mail.subject: 'Mirakl HiPay Connector Notification'
    mail.to: marketplace.operator@hipay.com
    mail.from: mirakl.hipay.connector@hipay.com

    # Other services launched with Docker Compose
    db.driver: 'pdo_mysql'
    db.host: db
    db.username: dev
    db.password: '123456'
    db.name: app
    db.port: 3306

    mail.host: smtp
    mail.port: 1025
    mail.security: null
    mail.username:
    mail.password:

    hipay.locale: 'fr_FR'
    hipay.timezone: 'Europe/Paris'
