<?php

namespace HiPay\Wallet\Mirakl\Integration\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogGeneralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogGeneralRepository extends AbstractTableRepository
{

    protected function getSelectString()
    {
        return 'a.createdAt, a.levelName, a.action, a.miraklId, a.message';
    }

    protected function getCountString()
    {
        return 'COUNT(a.id)';
    }

    protected function prepareAjaxRequest($queryBuilder, $search)
    {

        if (!empty($search)) {
            $queryBuilder->where(
                    $queryBuilder->expr()->orX(
                        $queryBuilder->expr()->like('a.miraklId', '?1')
                    )
                )
                ->setParameter(1, '%'.$search.'%');
        }

        return $queryBuilder;
    }
}